"use client";
import { useEffect, useRef, useState } from 'react';
import { completeDemoTask, demoDate, simulateDemoEmail, type DemoApplication, type DemoData, type DemoInterview, type DemoTask } from '@/lib/demo-data';
import { leaveDemo } from './login/actions';
const panel='rounded-2xl border border-black/[0.06] bg-white p-5 sm:p-6';
const button='rounded-xl bg-[#202522] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#3E4940] disabled:opacity-40';
type View='Today'|'Applications'|'Interviews'|'Email updates'|'Me';
type Modal={kind:'application'|'interview'|'email'|'reply';id:string}|null;
function Stage({stage}:{stage:string}){return <span className={`rounded-full px-3 py-1 text-xs font-medium ${stage==='Rejected'?'bg-neutral-100 text-neutral-500':stage==='Applied'?'bg-[#F1F2EF] text-[#65705E]':'bg-[#E8EFE7] text-[#466344]'}`}>{stage}</span>;}
export function DemoWorkspace({initial}:{initial:DemoData}) {
 const [data,setData]=useState(initial),[view,setView]=useState<View>('Today'),[query,setQuery]=useState(''),[stage,setStage]=useState('All'),[notice,setNotice]=useState(''),[modal,setModal]=useState<Modal>(null),[draft,setDraft]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const element=dialog.current;if(modal&&element){element.showModal();return()=>element.close();}},[modal]);
 const pending=data.tasks.filter(t=>!t.completed),responses=pending.filter(t=>t.kind!=='todo');
 const interviews=data.interviews.filter(i=>new Date(i.at)>new Date(data.now)).sort((a,b)=>a.at.localeCompare(b.at));
 const application=(id:string)=>data.applications.find(a=>a.id===id)!;
 function reply(task:DemoTask) {
  const app=application(task.applicationId),interview=data.interviews.find(i=>i.applicationId===app.id);
  setDraft(task.kind==='confirm'?`Hi ${interview?.interviewer.split(' · ')[0]??'team'},\n\nThank you for the invitation. ${demoDate(interview!.at)} works well for me. I look forward to discussing the ${app.role} role at ${app.company}.\n\nBest,\nAlex`:task.kind==='availability'?`Hi Sam,\n\nThank you for reaching out! I would be happy to discuss the ${app.role} role. I’m available ${demoDate(data.interviews[0].at)} or ${demoDate(data.interviews[1].at)}. Please let me know which time works best for your team.\n\nBest,\nAlex`:`Hi team,\n\nI wanted to follow up on my application for the ${app.role} role at ${app.company}. I remain interested and would be happy to share any additional information.\n\nBest,\nAlex`);
  setModal({kind:'reply',id:task.id});
 }
 function complete(task:DemoTask) {setData(value=>completeDemoTask(value,task.id,undefined,task.kind==='todo'?'':draft));setModal(null);setNotice(task.kind==='todo'?'Preparation task completed.':task.kind==='confirm'?'Interview time confirmed in the demo. No email was sent.':'Sample response recorded. No email was sent.');}
 function appCard(app:DemoApplication) {return <button key={app.id} onClick={()=>setModal({kind:'application',id:app.id})} className={`${panel} block w-full text-left transition hover:border-black/15`}><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-sm text-[#718071]">{app.company}</p><h3 className="mt-1 font-semibold">{app.role}</h3><p className="mt-2 text-xs text-neutral-400">{app.location}</p></div><Stage stage={app.stage}/></div><div className="mt-4 flex justify-between gap-3 text-xs text-neutral-400"><span>Applied {demoDate(app.appliedAt,false)}</span><span>Timeline & details →</span></div></button>;}
 function interviewCard(interview:DemoInterview) {const app=application(interview.applicationId),task=pending.find(t=>t.kind==='confirm'&&t.applicationId===app.id);return <article key={interview.id} className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium text-[#65705E]">{demoDate(interview.at)}</p><h3 className="mt-2 font-semibold">{app.company} · {interview.round}</h3><p className="mt-1 text-sm text-neutral-500">{app.role}</p></div><span className={`rounded-full px-3 py-1 text-xs ${interview.confirmed?'bg-[#E8EFE7] text-[#466344]':'bg-[#FBF0DD] text-[#916C31]'}`}>{interview.confirmed?'Confirmed':'Confirm date'}</span></div><p className="mt-4 text-xs text-neutral-400">{interview.minutes} minutes · Video call · {interview.interviewer}</p><div className="mt-4 flex flex-wrap items-center gap-4">{task&&<button className={button} onClick={()=>reply(task)}>Confirm time</button>}<button onClick={()=>setModal({kind:'interview',id:interview.id})} className="text-sm text-[#65705E] underline underline-offset-4">Details & preparation</button></div></article>;}
 const activeTask=modal?.kind==='reply'?data.tasks.find(t=>t.id===modal.id):null;
 const activeApp=modal?.kind==='application'?application(modal.id):null;
 const activeInterview=modal?.kind==='interview'?data.interviews.find(i=>i.id===modal.id):null;
 const activeEmail=modal?.kind==='email'?data.emails.find(e=>e.id===modal.id):null;
 return <main className="min-h-screen bg-[#F8F8F6] text-[#202522]">
  <aside className="border-b border-black/5 bg-white px-5 py-5 md:fixed md:inset-y-0 md:left-0 md:flex md:w-60 md:flex-col md:border-r md:px-6 md:py-8"><p className="mb-1 whitespace-nowrap text-base font-semibold tracking-tight">✦ Application Buddy</p><p className="mb-7 text-xs text-[#899384]">Your search, lighter.</p><nav aria-label="Demo navigation" className="flex gap-1 overflow-x-auto md:block md:space-y-1">{(['Today','Applications','Interviews','Email updates','Me'] as View[]).map(label=><button key={label} onClick={()=>setView(label)} aria-current={view===label?'page':undefined} className={`shrink-0 rounded-xl px-3 py-2.5 text-left text-sm md:w-full ${view===label?'bg-[#EDF0E8] font-medium text-[#466344]':'text-neutral-500 hover:bg-neutral-50'}`}>{label}</button>)}</nav><div className="mt-8 md:mt-auto"><p className="text-xs text-neutral-400">Alex Morgan · sample workspace</p><div className="mt-3 flex gap-4"><button onClick={()=>{setData(structuredClone(initial));setModal(null);setQuery('');setStage('All');setView('Today');setNotice('Demo reset to its starting point.');}} className="text-xs text-neutral-500 underline">Reset demo</button><form action={leaveDemo}><button className="text-xs text-neutral-500 underline">Sign out</button></form></div><p className="mt-6 text-xs text-neutral-300">Built by Macauley Deverin</p></div></aside>
  <div className="md:ml-60"><div className="mx-auto max-w-5xl px-5 py-7 sm:px-10 md:py-10">
   <div className="mb-8 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-[#EDEFE7] px-4 py-3 text-xs text-[#65705E]"><span><span className="font-semibold">Interactive demo</span> · Fictional sample data</span><span>Replies and email updates are simulated</span></div>
   <header className="mb-8"><p className="text-sm text-neutral-400">{demoDate(data.now,false)}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{view==='Today'?'Your next move, already organized.':view==='Me'?'Your workspace':view}</h1><p className="mt-3 text-neutral-500">{view==='Today'?'Applications tracked. Conversations connected. Next steps ready.':view==='Applications'?'Every application, with the context you need.':view==='Interviews'?'Know who you’re meeting, when, and what to prepare.':view==='Email updates'?'Relevant emails become progress—not another inbox to manage.':'A personal workspace that keeps your search moving.'}</p></header>
   {notice&&<div role="status" className="mb-6 flex items-center justify-between gap-4 rounded-xl border border-[#DEE5D8] bg-[#F0F4EB] px-4 py-3 text-sm text-[#466344]"><p>{notice}</p><button aria-label="Dismiss notification" onClick={()=>setNotice('')} className="text-lg">×</button></div>}
   {view==='Today'&&<>
    <div className="mb-8 grid grid-cols-3 gap-3">{[['Active applications',data.applications.filter(a=>a.stage!=='Rejected').length],['Upcoming interviews',interviews.length],['Responses needed',responses.length]].map(([label,count])=><div key={label} className={`${panel} !p-4 sm:!p-5`}><p className="text-xs text-neutral-500">{label}</p><p className="mt-3 text-3xl font-semibold">{count}</p></div>)}</div>
    <section className={`${panel} mb-8`}><div className="mb-1 flex justify-between"><h2 className="font-semibold">Needs you</h2><span className="text-xs text-neutral-400">{pending.length} next steps</span></div><p className="mb-2 text-sm text-neutral-400">Pulled from the conversation, so nothing gets lost.</p>{pending.map(task=><div key={task.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-black/5 py-4 last:border-0"><div><p className="text-sm font-medium">{task.title}</p><p className="mt-1 text-xs text-neutral-400">{application(task.applicationId).company} · Due {demoDate(task.due,false)}</p></div><button onClick={()=>task.kind==='todo'?complete(task):reply(task)} className={task.kind==='todo'?'rounded-xl border border-black/10 px-3 py-2 text-xs text-neutral-500':button}>{task.kind==='confirm'?'Confirm date':task.kind==='availability'?'Review reply':task.kind==='followup'?'Draft follow-up':'Mark complete'}</button></div>)}{!pending.length&&<p className="py-5 text-sm text-[#65705E]">Your next steps are taken care of.</p>}</section>
    <section className="mb-8"><div className="mb-4 flex justify-between"><h2 className="font-semibold">Upcoming interviews</h2><button onClick={()=>setView('Interviews')} className="text-sm text-[#65705E]">View all →</button></div><div className="space-y-4">{interviews.slice(0,2).map(interviewCard)}</div></section>
    <section><div className="mb-4 flex justify-between"><h2 className="font-semibold">Recent applications</h2><button onClick={()=>setView('Applications')} className="text-sm text-[#65705E]">View all →</button></div><div className="space-y-4">{[...data.applications].sort((a,b)=>(b.timeline.at(-1)?.at??b.appliedAt).localeCompare(a.timeline.at(-1)?.at??a.appliedAt)).slice(0,4).map(appCard)}</div></section>
   </>}
   {view==='Applications'&&<><div className="mb-6 flex flex-col gap-3 sm:flex-row"><input aria-label="Search applications" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company, role, or location…" className="w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-black/15"/><select aria-label="Filter applications by stage" value={stage} onChange={e=>setStage(e.target.value)} className="rounded-xl border border-black/10 bg-white px-4 py-3 text-sm"><option>All</option>{['Applied','Screening','Interview','Final','Offer','Rejected'].map(s=><option key={s}>{s}</option>)}</select></div><div className="space-y-4">{data.applications.filter(a=>(stage==='All'||a.stage===stage)&&`${a.company} ${a.role} ${a.location}`.toLowerCase().includes(query.toLowerCase())).map(appCard)}</div></>}
   {view==='Interviews'&&<div className="space-y-4">{interviews.map(interviewCard)}</div>}
   {view==='Email updates'&&<><div className={`${panel} mb-6 flex flex-wrap items-center justify-between gap-5`}><div><h2 className="font-semibold">See an email become a next step.</h2><p className="mt-2 max-w-lg text-sm leading-relaxed text-neutral-500">Try a sample application confirmation, then an interview request. Watch the tracker, timeline, and to-dos update together.</p></div><button disabled={data.simulation>=2} className={button} onClick={()=>{setData(value=>simulateDemoEmail(value));setNotice(data.simulation===0?'A new application was added automatically from the sample email.':'An interview and confirmation task were added from the sample email.');}}>{data.simulation===0?'Try a confirmation email':data.simulation===1?'Try an interview request':'Both sample emails organized ✓'}</button></div><div className="space-y-4">{data.emails.map(email=><article key={email.id} className={panel}><p className="text-xs text-neutral-400">{application(email.applicationId).company} · {demoDate(email.receivedAt,false)}</p><h2 className="mt-2 font-semibold">{email.subject}</h2><p className="mt-3 text-sm text-[#65705E]">✓ {email.result}</p><button onClick={()=>setModal({kind:'email',id:email.id})} className="mt-4 text-sm text-neutral-500 underline underline-offset-4">View sample source email</button></article>)}</div></>}
   {view==='Me'&&<div className="space-y-5"><section className={panel}><h2 className="font-semibold">Sample candidate</h2><p className="mt-3 text-sm text-neutral-500">Alex Morgan · Product & Operations</p><p className="mt-2 text-xs text-neutral-400">alex@example.com · fictional profile</p></section><section className={panel}><h2 className="font-semibold">Email connection</h2><p className="mt-3 text-sm text-neutral-500">This walkthrough uses sample emails. No personal mailbox is connected.</p><button onClick={()=>setView('Email updates')} className="mt-4 text-sm text-[#65705E] underline">Explore sample email updates →</button></section><section className={panel}><h2 className="font-semibold">The idea</h2><p className="mt-3 text-sm leading-relaxed text-neutral-500">A job search creates dozens of scattered conversations. Application Buddy connects them to the right application and surfaces the next action—so the user can spend less time maintaining a tracker and more time preparing for the opportunity.</p></section></div>}
  </div></div>
  {modal&&<dialog ref={dialog} onCancel={()=>setModal(null)} aria-labelledby="demo-dialog-heading" className="fixed inset-0 m-auto max-h-[85vh] w-[calc(100%-2rem)] max-w-2xl overflow-auto rounded-2xl bg-white p-6 text-[#202522] shadow-xl backdrop:bg-black/35 sm:p-8"><div className="mb-5 flex items-start justify-between gap-5"><h2 id="demo-dialog-heading" className="text-xl font-semibold">{activeTask?activeTask.title:activeApp?`${activeApp.company} · ${activeApp.role}`:activeInterview?`${application(activeInterview.applicationId).company} · ${activeInterview.round}`:activeEmail?.subject}</h2><button aria-label="Close details" onClick={()=>setModal(null)} className="rounded-full px-2 text-2xl text-neutral-400">×</button></div>
   {activeTask&&<><p className="mb-4 text-sm text-neutral-500">{application(activeTask.applicationId).company} · Edit the suggested response if you like.</p><label htmlFor="demo-reply" className="mb-2 block text-xs text-neutral-400">Suggested reply</label><textarea id="demo-reply" value={draft} onChange={e=>setDraft(e.target.value)} rows={10} className="w-full rounded-xl border border-black/15 bg-[#FAFAF8] p-4 text-sm leading-relaxed outline-none focus:ring-2 focus:ring-black/15"/><p className="mt-3 text-xs text-neutral-400">Sample response only. No email is sent from the demo.</p><button disabled={!draft.trim()} className={`${button} mt-5`} onClick={()=>complete(activeTask)}>Send sample reply</button></>}
   {activeApp&&<><div className="flex flex-wrap items-center gap-3"><Stage stage={activeApp.stage}/><span className="text-sm text-neutral-400">{activeApp.location}</span></div><p className="mt-5 text-sm text-neutral-500">Sample resume version: {activeApp.resume}</p><h3 className="mb-4 mt-7 text-sm font-semibold">Application timeline</h3><ol className="space-y-5">{[...activeApp.timeline].reverse().map((event,index)=><li key={`${event.at}-${index}`} className="border-l-2 border-[#DFE5D8] pl-4"><p className="text-xs text-neutral-400">{demoDate(event.at,false)}</p><p className="mt-1 text-sm font-medium">{event.title}</p><p className="mt-1 whitespace-pre-wrap text-sm text-neutral-500">{event.detail}</p></li>)}</ol><button className="mt-6 text-sm text-[#65705E] underline" onClick={()=>{setModal(null);setView('Email updates');}}>See the sample source emails →</button></>}
   {activeInterview&&<><p className="text-sm font-medium text-[#65705E]">{demoDate(activeInterview.at)} · {activeInterview.minutes} minutes</p><p className="mt-4 text-sm text-neutral-500">{activeInterview.interviewer}</p><p className="mt-2 text-sm text-neutral-400">Video call · {activeInterview.confirmed?'Time confirmed':'Confirmation requested'}</p><h3 className="mt-7 text-sm font-semibold">Prepare for this conversation</h3><p className="mt-3 text-sm leading-relaxed text-neutral-500">{activeInterview.notes}</p><button onClick={()=>{const task=pending.find(t=>t.kind==='confirm'&&t.applicationId===activeInterview.applicationId);if(task)reply(task);else setModal({kind:'application',id:activeInterview.applicationId});}} className={`${button} mt-6`}>{activeInterview.confirmed?'Open application timeline':'Confirm interview date'}</button></>}
   {activeEmail&&<><p className="text-xs text-neutral-400">Sample email · {activeEmail.from} · {demoDate(activeEmail.receivedAt)}</p><p className="mt-5 whitespace-pre-wrap text-sm leading-relaxed text-neutral-600">{activeEmail.body}</p><div className="mt-6 rounded-xl bg-[#EDF0E8] p-4 text-sm text-[#65705E]">✓ {activeEmail.result}</div><button onClick={()=>setModal({kind:'application',id:activeEmail.applicationId})} className="mt-5 text-sm text-[#65705E] underline">Open linked application →</button></>}
  </dialog>}
 </main>;
}
